title: dev.joynt.co.uk
author:
  name: Charles Joynt
description: >
  A showcase of personal projects using Python and PowerShell, AI applications
  including ChatGPT GPTs.

# theme: minima
# As of November 2023, GitHub Pages still uses Minima 2.5.1 (https://pages.github.com/versions/). 
# If you want to use the latest Minima version on GitHub Pages, use the following setting and 
# add a line comment on "theme: minima" above.
remote_theme: jekyll/minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - blog.md
  - downthetube.md
  - spelling_test.md

show_excerpts: true

minima:
  skin: dark
  social_links:
    - { platform: github, user_url: "https://github.com/cjj1977" }
    - { platform: stackoverflow,  user_url: "https://stackoverflow.com/users/5771128/misterseajay" }
