title: dev.joynt.co.uk
description: Personal Projects Showcase

theme: minima

minima:
  skin: dark
  social_links:
    github: cjj1977
    stackoverflow: misterseajay

header_pages:
  - blog.md
  - downthetube.md
  - spelling_test.md

show_excerpts: true