title: dev.joynt.co.uk
description: Personal Projects Showcase
theme: minima
minima:
  skin: dark
  social_links:
    - { platform: github, user_url: "https://github.com/cjj1977" }
    - { platform: stackoverflow, user_url: "https://stackoverflow.com/users/5771128" }
header_pages:
  - blog.md
  - downthetube.md
  - spelling_test.md
show_excerpts: true